# Generated by Django 3.2 on 2023-03-11 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20, verbose_name='Marca')),
                ('model', models.CharField(max_length=20, verbose_name='Modelo')),
                ('color', models.CharField(max_length=20, verbose_name='Cor')),
                ('license_plate', models.CharField(max_length=7, unique=True, verbose_name='Placa')),
            ],
        ),
        migrations.CreateModel(
            name='CarStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_in', models.DateTimeField(auto_now=True, verbose_name='entrada')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.car')),
            ],
        ),
    ]
