# Generated by Django 3.2 on 2023-03-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(max_length=8, unique=True, verbose_name='Placa'),
        ),
    ]
