# Generated by Django 3.2 on 2023-03-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_car_license_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carstack',
            name='input_in',
            field=models.DateTimeField(auto_now_add=True, verbose_name='entrada'),
        ),
    ]
